import React, { Component } from 'react';
import './App.css';
import NavBar from './nav/NavBar';
import StudentBlock from './student-cards/StudentBlock';
import GroupTech from './groupTech/groupTech'

class App extends Component {

  // initial state of application, holds student information
  state = {
    students: [
      {first_name: 'Cashew', last_name: 'Agnoletti', serious_photo: '', fun_photo: '', github: 'https://github.com/CashewRose', linkedin: 'https://www.linkedin.com/in/cashew-agnoletti', email: 'danieagnoletti@gmail.com', personal_website: 'URL TK', other_website: '', other_website_description: '', preferred_skill: 'React and JavaScript', bio: 'As an avid gamer who is familiar with a computer I fell in love with programming.'},
      {first_name: 'Erin', last_name: 'Agobert', serious_photo: '', fun_photo: '', github: 'https://github.com/eagobert', linkedin: 'https://www.linkedin.com/in/eagobert/', email: 'eagobert@hotmail.com', personal_website: 'www.erinagobert.com', other_website: '', other_website_description: '', preferred_skill: "I'm very interested in exploring how different technologies and programming languages are used for data exploration. I would like to expand on my training in Python and C#, delving into the various packages for data management and analysis", bio: "Air Force veteran and former federal administrator turned budding full-stack software developer. I have a passion for designing and developing information retrieval systems and data visualizations"},
      {first_name: 'Rachael', last_name: 'Babcock', serious_photo: '', fun_photo: '', github: 'https://github.com/rsbabcock', linkedin: 'https://www.linkedin.com/in/rachael-babcock/', email: 'rachael.s.babcock@gmail.com', personal_website: 'http://rachaelbabcock.com/', other_website: 'https://twitter.com/r_s_babcock', other_website_description: 'Twitter', preferred_skill: "I'm interested in Full-Stack Development, VR and 3D Animation", bio: 'A former Animation Producer turned Software Developer, development is where my need to create and passion for solving problems meet. Passionate about fun design and delivering clear, readable and efficient code.'},
      {first_name: 'Josh', last_name: 'Barton', serious_photo: '', fun_photo: '', github: 'https://github.com/joshdbarton', linkedin: 'https://www.linkedin.com/in/joshdbarton/', email: 'joshdbarton@gmail.com', personal_website: 'joshdbarton.me', other_website: '', other_website_description: '', preferred_skill: 'Full-Stack, React.js, Python', bio: "A former rabbi, I'm interested in being part of a thoughtful and deliberate software development team, and excited about making software that help people lead healthier, more skillful lives."},
      {first_name: 'Daniel', last_name: 'Beecroft', serious_photo: '', fun_photo: '', github: 'https://github.com/binauralbeat', linkedin: 'https://www.linkedin.com/in/daniel-beecroft-2081a7102/', email: 'binauralbeat001@gmail.com', personal_website: 'binauralbeat.github.io', other_website: '', other_website_description: '', preferred_skill: 'full stack with Python/Django, JavaScript/React and Adobe Creative Cloud', bio: 'Graphic designer and musician turned developer. Always looking for creative solutions for marketing, design and software development.'},
      {first_name: 'Jake', last_name: 'Carter', serious_photo: '', fun_photo: '', github: 'https://github.com/jcarter0149', linkedin: 'https://www.linkedin.com/in/jake-carter/', email: 'jacobraycarter@gmail.com', personal_website: '', other_website: '', other_website_description: '', preferred_skill: 'Security Clearance, Javascript, React, WordPress, Python, Django, Data mining', bio: 'Former military intelligence analyst looking to bring my unique skillset and outlook of life to the world of software development. You can probably find me in the gym.'},
      {first_name: 'Rafael', last_name: 'Cevallos', serious_photo: '', fun_photo: '', github: 'https://github.com/rafcevallos', linkedin: 'https://www.linkedin.com/in/rafaelcevallos/', email: 'rafael.cevallos81@gmail.com', personal_website: 'https://www.rafcevallos.com/', other_website: '', other_website_description: '', preferred_skill: 'JavaScript, React, Python, and Django', bio: 'Native Nashvillian, musician, teacher, comic book lover, film aficionado, nature enthusiast, and lifelong learner turned software developer who dreams of Tasmania, navigating different cultures and ideas, advocating for the marginalized, being better than the day before, and living life with purpose.'},
      {first_name: 'Meghan', last_name: 'Debity', serious_photo: '', fun_photo: '', github: 'https://github.com/Megraohoh', linkedin: 'https://www.linkedin.com/in/meghan-debity/', email: 'mdebity@gmail.com', personal_website: 'meghandebity.com', other_website: 'https://www.facebook.com/meghan.debity', other_website_description: 'Facebook', preferred_skill: 'Javascript, jQuery, Python, Django, pointing out things', bio: "Problem solving and puzzles have become my daily passion, whether it's in code or a Sudoku book. I have found that finding solutions is a natural way for me to help others."},
      {first_name: 'Cole', last_name: 'Doster', serious_photo: '', fun_photo: '', github: 'https://github.com/wcdoster', linkedin: 'https://www.linkedin.com/in/cole-doster-990149aa/', email: 'wcdoster@gmail.com', personal_website: 'URL TK', other_website: '', other_website_description: '', preferred_skill: 'JavaScript, Python', bio: 'I am Nashville native, who graduated from the University of Tennessee, Knoxville, with a degree in Civil/Environmental Engineering. After spending the last few years managing a restaurant, I am excited to jumpstart my new career in software development.'},
      {first_name: 'Katheryn', last_name: 'Ford', serious_photo: '', fun_photo: '', github: 'https://github.com/AnEvilHerbivore', linkedin: 'https://www.linkedin.com/in/katheryn-ford-273286166/', email: 'AnEvilHerbivoreLP@gmail.com', personal_website: '', other_website: '', other_website_description: '', preferred_skill: 'Javascript, Python, Django', bio: 'Excitable, passionate girl with an interest in both front end and back end programming.'},
      {first_name: 'Sean', last_name: 'Irwin', serious_photo: '', fun_photo: '', github: 'https://github.com/sirwin4', linkedin: 'https://www.linkedin.com/in/sean-irwin-7278b0167/', email: 'sean.irwinxc@gmail.com', personal_website: '', other_website: '', other_website_description: '', preferred_skill: 'JavaScript, Python, Django, React', bio: 'New developer ready to apply research skills from a soil microbiology background to another field of study'},
      {first_name: 'Matthew', last_name: 'Kelly', serious_photo: '', fun_photo: '', github: 'https://github.com/MatthewKelly12', linkedin: 'https://www.linkedin.com/in/matthew-kelly-22465915b/', email: 'mkonabike@gmail.com', personal_website: '', other_website: '', other_website_description: '', preferred_skill: 'JavaScript, Canvas, Animation', bio: 'I was born and raised in Nashville, TN and I enjoy math, music, gardening, mountain biking, and dogs.'},
      {first_name: 'Hayley', last_name: 'Landsberg', serious_photo: '', fun_photo: '', github: 'https://github.com/hayleylandsberg', linkedin: 'www.linkedin.com/in/hayleyvheath', email: 'hayleylandsberg@gmail.com', personal_website: 'www.hayleylandsberg.com', other_website: 'dribbble.com/hayleylandsberg', other_website_description: 'Dribbble', preferred_skill: 'Front End Development, React, Javascript, CSS', bio: "A risk management professional turned UX/UI Designer & Developer. I'm passionate about the user's experience and appreciate design thinking."},
      {first_name: 'Riley', last_name: 'Mathews', serious_photo: '', fun_photo: '', github: 'https://github.com/RileyMathews', linkedin: 'https://www.linkedin.com/in/riley-mathews-12a243b4/', email: 'riley@rileymathews.com', personal_website: 'rileymathews.com', other_website: '', other_website_description: '', preferred_skill: 'Javascript. Python/Django', bio: "I am a musician and producer turned software developer. I'm looking forward to what this new journey has in store."},
      {first_name: 'Erin', last_name: 'Meaker', serious_photo: '', fun_photo: '', github: 'https://github.com/MrErin', linkedin: 'www.linkedin.com/in/erin-meaker', email: 'erinmeaker@gmail.com', personal_website: 'erinmeaker.com', other_website: '', other_website_description: '', preferred_skill: 'I love working through any problem that involves data analysis or complex logic. ', bio: 'Chaos tamer. Problem solver. Data spelunker. Insatiable learner. Optimizer. Innovator. Slayer of bugs.'},
      {first_name: 'Patrick', last_name: 'Murphy', serious_photo: '', fun_photo: '', github: 'https://github.com/pwmurphy89', linkedin: 'https://www.linkedin.com/in/patrick-murphy-12561166/', email: 'pwmurphy89@gmail.com', personal_website: 'www.pwmurphy.com', other_website: '', other_website_description: '', preferred_skill: 'JavaScript', bio: 'I have a lot of interests.'},
      {first_name: 'David', last_name: 'Paul', serious_photo: '', fun_photo: '', github: 'https://github.com/obscure-shadow', linkedin: 'https://www.linkedin.com/in/david-paul-93267079/', email: 'dfp333@gmail.com', personal_website: 'URL TK', other_website: '', other_website_description: '', preferred_skill: 'DevOps and Security', bio: 'I like things. Sometimes I also like stuff. Also, learn vim.'},
      {first_name: 'Jonny', last_name: 'Riggs', serious_photo: '', fun_photo: '', github: 'https://github.com/Jonny-Riggs', linkedin: 'www.linkedin.com/in/jonnyriggs615', email: 'jonny.riggs615@gmail.com', personal_website: 'URL TK', other_website: 'https://twitter.com/_jonny_riggs', other_website_description: 'Twitter', preferred_skill: 'Full Stack - Javascript/React and Python/Django', bio: 'Nashville native and musician with a serious passion for all things software development.'},
      {first_name: 'Levi', last_name: 'Schubert', serious_photo: '', fun_photo: '', github: 'https://github.com/Levi-Schubert', linkedin: 'www.linkedin.com/in/Levi-Schubert', email: 'me@LeviSchubert.com', personal_website: 'http://levischubert.com', other_website: '', other_website_description: '', preferred_skill: 'Python, Django, TDD, React, Javascript', bio: 'Helping others and creating large scale, interesting, and useful applications are important goals and passions. I hold high standards for myself and continually aim to improve and learn.'},
      {first_name: 'Jacob Andrew', last_name: 'Smith', serious_photo: '', fun_photo: '', github: 'https://github.com/JacobAndrewSmith92', linkedin: 'https://www.linkedin.com/in/jacob-smith-847201b2/', email: 'jacobandrewsmith92@gmail.com', personal_website: 'jacobandrew.co', other_website: '', other_website_description: '', preferred_skill: 'Javascript | React.js | Design | Product Development | Python | Django', bio: 'My name is Jacob and I am a relation-centered software developer. Motivated to build useful, systematic software that solves problems and keeps the focus on what really matters, people.'},
      {first_name: 'Jessica', last_name: 'Swift', serious_photo: '', fun_photo: '', github: 'https://github.com/jessnswift', linkedin: 'https://www.linkedin.com/in/jessica-swift-4b549623/', email: 'jessica.nicole.swift@gmail.com', personal_website: 'https://jessicaswift.codes', other_website: '', other_website_description: '', preferred_skill: 'Front End Web Developer, Python, Javascript, bootstrap, React, django, sqlite, css.....the list goes on....', bio: "Hi, I'm Jessica."},
      {first_name: 'Dillan', last_name: 'Teagle', serious_photo: '', fun_photo: '', github: 'https://github.com/teaglebuilt', linkedin: 'https://www.linkedin.com/in/teaglebuilt', email: 'dillan.teagle.va@gmail.com', personal_website: 'dillanteagle.me', other_website: '', other_website_description: '', preferred_skill: 'javascript, react, python, django, sql, css, adobe creative cloud', bio: 'Typical veteran that found out he would rather be a nerd than a soldier. To have a career where I always have more to learn and achieve sets me on a constant pursuit of progression, this is more than I could ever ask for in a career.'},
      {first_name: 'Deanna', last_name: 'Vickers', serious_photo: '', fun_photo: '', github: 'https://github.com/Deanna2000', linkedin: 'https://www.linkedin.com/in/deannavickers/', email: 'deanna2000@gmail.com', personal_website: 'www.deannavickers.com', other_website: 'https://twitter.com/Deanna2000', other_website_description: 'Twitter', preferred_skill: 'I like learning new technologies and frameworks and I really enjoy creating fun user experiences. I also love pair programming.', bio: "I am a maker and I'm thrilled to be learning another medium for making things."},
      {first_name: 'Ronnie', last_name: 'Young', serious_photo: '', fun_photo: '', github: 'https://github.com/Ryoung27', linkedin: 'https://www.linkedin.com/in/ronnie-young-bb59a2119/', email: 'RRYoung89@gmail.com', personal_website: 'https://ryoung27.github.io/', other_website: '', other_website_description: '', preferred_skill: 'I want to work with things that are technically challenging in the software field. I am an extrovert and enjoy the humanities.', bio: 'I arise in the morning torn between a desire to improve the world and a desire to enjoy the world. This makes it difficult to plan the day.'},
      {first_name: 'Paul', last_name: 'Zimmerman-Clayton', serious_photo: '', fun_photo: '', github: 'https://github.com/paulzimmclay', linkedin: 'https://www.linkedin.com/in//paulzc', email: 'paul.zimmerman.clayton@gmail.com', personal_website: 'URL TK', other_website: '', other_website_description: '', preferred_skill: 'Want to work with: JavaScript, React, Python, Django. Existing skills in: Operations, Implementation, Customer Support, Documentation', bio: "Ask questions, listen, and understand as completely as possible the problem to be solved - these are the most important things I've learned while working directly with customers and enabling my teammates. I'm excited to work with an experienced development team to learn how to define and solve a new set of challenges."}
    ]
  }

  render() {
    return (
      <div>
        <NavBar/>
        <StudentBlock 
          students={this.state.students}
        />
        <GroupTech/>
      </div>
    );
  }
}

export default App;
